language: python
matrix:
  include:
    - os: windows
      language: sh
      python: 3
      # Perform the manual steps on windows to install python3
      before_install:
        - choco install python3 --params "/InstallDir:C:\Python"
        - export PATH="/c/Python:/c/Python/Scripts:$PATH"
        - python -m pip install --upgrade pip
        - python -m pip install pywin32
      before_script:
        - export TOXENV=py3-win

    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    # Obtain Python 3.7 from xenial as per https://github.com/travis-ci/travis-ci/issues/9815
    - python: "3.7"
      dist: xenial

    - python: "2.7"
      arch: ppc64le
    - python: "3.6"
      arch: ppc64le
    # Obtain Python 3.7 from xenial as per https://github.com/travis-ci/travis-ci/issues/9815
    - python: "3.7"
      dist: xenial
    - python: "3.8"
      dist: bionic
install:
  - pip install tox
before_script:
  - export TOXENV=$(echo py$TRAVIS_PYTHON_VERSION | tr -d .)
script:
  - tox
