language: python
matrix:
  include:
    - os: windows
      language: sh
      python: "3.8"
      env: "PATH="/c/Python:/c/Python/Scripts:$PATH""
      # Perform the manual steps on windows to install python3
      before_install:
        - choco install python --version=3.8.6
        - python -m pip install --upgrade pip
      before_script:
        - export TOXENV=py38
    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - python: "3.9"
    - python: "nightly"  # 3.10
      before_script:
        - export TOXENV=py310
    - python: "2.7"
      arch: ppc64le
    - python: "3.6"
      arch: ppc64le
        
install:
  - python -m pip install tox
before_script:
  - export TOXENV=$(echo py$TRAVIS_PYTHON_VERSION | tr -d .)
script:
  - python -m tox
