language: python
matrix:
  include:
    - python: "3.4"
    - python: "2.7"
      arch: ppc64le
    - python: "3.6"
      arch: ppc64le
    - python: "3.7"
      arch: ppc64le
    - python: "3.8"
      arch: ppc64le
    - python: "3.9"
      arch: ppc64le
install:
  - python -m pip install tox
before_script:
  - export TOXENV=$(echo py$TRAVIS_PYTHON_VERSION | tr -d .)
script:
  - python -m tox
